<?xml version="1.0"?>
<package format="2">
  <name>pal_sea_arm_simulation</name>
  <version>0.0.0</version>
  <description>The pal_sea_arm_simulation package</description>

  <maintainer email="narcis.miguel@pal-robotics.com">Narcis Miguel</maintainer>

  <license>Propietary</license>

  <buildtool_depend>catkin</buildtool_depend>
  <exec_depend>pal_sea_arm_gazebo</exec_depend>

  <export>
    <metapackage/>
  </export>
</package>
